services:
  - type: web
    name: pinguinmobile
    env: go
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: 11052004ARAd.
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: FamilyManagement
      - key: FIREBASE_CREDENTIALS_PATH
        value: pinguin-46f73-firebase-adminsdk-fbsvc-8854eaf409.json
